MDS-347 | Added logic for v2 endpoints
hmrc/individuals-matching-api pull request #31
Opened 2020-11-30 16:30 UTC by owen-opencast

2020-11-30 17:28 UTC, parkeradam approved these changes

2020-12-01 08:50 UTC, ajchilts requested changes
Nothing major in the comments. Looks great :-) 

One potential change if we think it is valid.

2020-12-01 08:50 UTC, ajchilts commented on app/uk/gov/hmrc/individualsmatchingapi/controllers/CommonController.scala
> +  def requiresPrivilegedAuthentication(endpointScopes: Iterable[String])(f: Iterable[String] => Future[Result])(
Should the common controller be in a V2 namespace to ensure it is never pulled into V1?

2020-12-01 08:50 UTC, ajchilts commented on app/uk/gov/hmrc/individualsmatchingapi/controllers/v2/PrivilegedCitizenMatchingController.scala
> +            title = Option("Individual Details"))
Could this cause confusion with the Individuals Details API? Do we need to rethink this title? Maybe one for Lisa?

2020-12-01 08:50 UTC, ajchilts commented on test/component/uk/gov/hmrc/individualsmatchingapi/controllers/v2/PrivilegedCitizenMatchingControllerSpec.scala
> +                 "title": "Individual Details"
Title may change to something less conflicting with Individuals Details after a chat with Lisa.

2020-12-01 08:56 UTC, ajchilts approved these changes

2020-12-01 11:18 UTC, merged